PRAGMA foreign_keys=OFF;
DELETE FROM cart_items;
DELETE FROM carts;
DELETE FROM products;
PRAGMA foreign_keys=ON;

INSERT INTO products (name, description, price, stock) VALUES ('Pantalón XXL Verde', '[Deportivo] Ideal para uso diario.', 1058, 177);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta XXL Blanco', '[Deportivo] Prenda cómoda y ligera.', 510, 33);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Negro', '[Casual] Diseño moderno y elegante.', 1292, 457);
INSERT INTO products (name, description, price, stock) VALUES ('Falda S Blanco', '[Casual] Ideal para uso diario.', 1138, 414);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XL Verde', '[Formal] Diseño moderno y elegante.', 603, 151);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta S Amarillo', '[Deportivo] Prenda cómoda y ligera.', 961, 223);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón L Gris', '[Deportivo] Diseño moderno y elegante.', 1331, 436);
INSERT INTO products (name, description, price, stock) VALUES ('Falda XXL Blanco', '[Casual] Prenda cómoda y ligera.', 1286, 441);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera L Azul', '[Casual] Material de alta calidad.', 889, 187);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón XXL Gris', '[Formal] Diseño moderno y elegante.', 647, 462);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta S Azul', '[Deportivo] Material de alta calidad.', 464, 65);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón M Blanco', '[Formal] Material de alta calidad.', 786, 65);
INSERT INTO products (name, description, price, stock) VALUES ('Falda XL Azul', '[Deportivo] Material de alta calidad.', 762, 454);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta L Gris', '[Casual] Diseño moderno y elegante.', 430, 193);
INSERT INTO products (name, description, price, stock) VALUES ('Falda L Azul', '[Deportivo] Prenda cómoda y ligera.', 952, 246);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Azul', '[Deportivo] Material de alta calidad.', 1128, 348);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta XXL Rojo', '[Deportivo] Diseño moderno y elegante.', 1292, 302);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón L Verde', '[Formal] Material de alta calidad.', 1017, 334);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón S Verde', '[Casual] Prenda cómoda y ligera.', 525, 257);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera S Negro', '[Deportivo] Perfecta para actividades al aire libre.', 596, 166);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera S Verde', '[Casual] Ideal para uso diario.', 967, 64);
INSERT INTO products (name, description, price, stock) VALUES ('Falda XL Negro', '[Deportivo] Perfecta para actividades al aire libre.', 464, 196);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta XL Amarillo', '[Casual] Diseño moderno y elegante.', 1465, 282);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa M Verde', '[Casual] Ideal para uso diario.', 1100, 206);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Rojo', '[Deportivo] Perfecta para actividades al aire libre.', 1010, 298);
INSERT INTO products (name, description, price, stock) VALUES ('Falda M Azul', '[Deportivo] Diseño moderno y elegante.', 1120, 482);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa XXL Verde', '[Deportivo] Diseño moderno y elegante.', 783, 264);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XXL Amarillo', '[Deportivo] Material de alta calidad.', 1261, 194);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera S Negro', '[Formal] Ideal para uso diario.', 925, 208);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón XXL Rojo', '[Formal] Material de alta calidad.', 1379, 19);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón M Verde', '[Casual] Diseño moderno y elegante.', 1338, 340);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta M Rojo', '[Deportivo] Material de alta calidad.', 777, 142);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta S Amarillo', '[Casual] Diseño moderno y elegante.', 1089, 333);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XXL Rojo', '[Formal] Perfecta para actividades al aire libre.', 1271, 304);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Azul', '[Deportivo] Diseño moderno y elegante.', 424, 443);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XL Rojo', '[Deportivo] Material de alta calidad.', 840, 376);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa S Rojo', '[Formal] Perfecta para actividades al aire libre.', 1090, 121);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta XXL Amarillo', '[Formal] Ideal para uso diario.', 548, 480);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XL Blanco', '[Deportivo] Ideal para uso diario.', 717, 248);
INSERT INTO products (name, description, price, stock) VALUES ('Falda M Blanco', '[Casual] Diseño moderno y elegante.', 1071, 323);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón XL Azul', '[Deportivo] Diseño moderno y elegante.', 815, 405);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa L Blanco', '[Casual] Diseño moderno y elegante.', 551, 111);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Rojo', '[Casual] Diseño moderno y elegante.', 1049, 37);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta XL Gris', '[Deportivo] Ideal para uso diario.', 1052, 260);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón M Verde', '[Deportivo] Perfecta para actividades al aire libre.', 960, 405);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta XXL Negro', '[Formal] Material de alta calidad.', 1055, 297);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta S Verde', '[Formal] Perfecta para actividades al aire libre.', 1180, 473);
INSERT INTO products (name, description, price, stock) VALUES ('Falda M Gris', '[Deportivo] Material de alta calidad.', 874, 374);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa XL Azul', '[Deportivo] Perfecta para actividades al aire libre.', 1151, 441);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa L Negro', '[Deportivo] Ideal para uso diario.', 835, 486);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta L Blanco', '[Casual] Ideal para uso diario.', 1070, 320);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta L Amarillo', '[Casual] Diseño moderno y elegante.', 1356, 148);
INSERT INTO products (name, description, price, stock) VALUES ('Falda L Gris', '[Deportivo] Material de alta calidad.', 1283, 252);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta S Verde', '[Formal] Ideal para uso diario.', 507, 136);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta L Azul', '[Casual] Perfecta para actividades al aire libre.', 407, 18);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta M Gris', '[Formal] Prenda cómoda y ligera.', 457, 360);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta L Blanco', '[Deportivo] Ideal para uso diario.', 445, 103);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera M Negro', '[Casual] Diseño moderno y elegante.', 1008, 319);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XXL Rojo', '[Casual] Perfecta para actividades al aire libre.', 1167, 218);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa M Rojo', '[Casual] Material de alta calidad.', 527, 19);
INSERT INTO products (name, description, price, stock) VALUES ('Falda L Verde', '[Casual] Ideal para uso diario.', 1390, 317);
INSERT INTO products (name, description, price, stock) VALUES ('Camisa M Azul', '[Casual] Material de alta calidad.', 1438, 253);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta L Verde', '[Formal] Perfecta para actividades al aire libre.', 778, 449);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta M Verde', '[Formal] Perfecta para actividades al aire libre.', 404, 350);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Gris', '[Casual] Ideal para uso diario.', 987, 226);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta L Blanco', '[Deportivo] Material de alta calidad.', 599, 100);
INSERT INTO products (name, description, price, stock) VALUES ('Pantalón XL Gris', '[Casual] Diseño moderno y elegante.', 756, 249);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta XL Negro', '[Formal] Perfecta para actividades al aire libre.', 541, 245);
INSERT INTO products (name, description, price, stock) VALUES ('Falda L Negro', '[Deportivo] Prenda cómoda y ligera.', 975, 480);
INSERT INTO products (name, description, price, stock) VALUES ('Falda XXL Azul', '[Formal] Perfecta para actividades al aire libre.', 973, 51);
INSERT INTO products (name, description, price, stock) VALUES ('Sudadera XXL Azul', '[Casual] Perfecta para actividades al aire libre.', 1491, 114);
INSERT INTO products (name, description, price, stock) VALUES ('Camiseta S Verde', '[Formal] Ideal para uso diario.', 1067, 391);
INSERT INTO products (name, description, price, stock) VALUES ('Chaqueta XL Rojo', '[Deportivo] Diseño moderno y elegante.', 1117, 347);